# Generated by Django 3.2.4 on 2021-06-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='creacion_u',
            new_name='creacion_usuario',
        ),
    ]
