# Generated by Django 3.2.4 on 2021-06-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_creacion_u_creacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacion_usuario',
            name='genero_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero', verbose_name='genero'),
        ),
    ]
